### ISSUE TITLE
Job Titles are limited

### ISSUE THREAD

**Issue by VickiLanger** [StateOfJS/StateOfJS-Vulcan#70]
There are several option for job titles, but I'm pretty sure this isn't even close to enough. If this survey is meant to be taken be all people who use JS, this will give incredibly skewed results. The best option would be to allow people write in their job title.

This list is at least missing pentesting, devops, are, instructors, network stuff, infosec, SEO, and many more

For reference, here's the current[ job title question](https://github.com/StateOfJS/StateOfJS-Vulcan/blob/master/packages/stateofjs/lib/surveys/yml/js2020outline.yml#L466)
```
      - id: job_title
        template: single
        allowother: true
        options:
          - id: cto
          - id: front_end_developer
          - id: full_stack_developer
          - id: back_end_developer
          - id: web_developer
          - id: web_designer
```
