### ISSUE TITLE
Gender question

### ISSUE THREAD

**Issue by VickiLanger** [StateOfJS/StateOfJS-Vulcan#72]
What is the goal of asking for gender/sex in these surveys?

For reference, here's the current[ gender question](https://github.com/StateOfJS/StateOfJS-Vulcan/blob/a63c442f5c31c1a43545bea74421c72dd7b8509f/packages/stateofjs/lib/surveys/yml/js2020outline.yml#L499)
```
      - id: gender
        template: single
        allowother: true
        options:
          - id: female
          - id: male
          - id: non_binary
          - id: prefer_not_to_say
```
